---

- name: Kubernetes reset
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: Create Kubernetes config directory
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy kubeconfig from host machine to config directory
  copy:
    src:  /tmp/kubeconfig
    dest: /root/.kube/config

- name: Kubernetes join cluster
  shell: >
    kubeadm join --discovery-file /root/.kube/config
    --ignore-preflight-errors=all
  register: kubeadm_join

- name: Restart Kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: kubeadm_join is succeeded
  register: kubelet_restarted

- name: Kubernetes get nodes
  shell: kubectl get nodes
  register: kubectl_get_nodes
  when: kubelet_restarted is succeeded

