---

- name: Kubernetes join cluster
  shell: >
    kubeadm join
    --ignore-preflight-errors=all
    --token {{ hostvars[groups['master'][0]]['ansible_facts']['kubeadm_token'] }}
    {{ groups['master'][0] }}:6643
    --discovery-token-unsafe-skip-ca-verification
    #--discovery-token-ca-cert-hash
    #sha256:{{ hostvars[groups['master'][0]]['ansible_facts']['kubeadm_x509_token'] }}
  register: kubeadm_join

- name: Restart Kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_restarted

- name: Kubernetes get nodes
  shell: kubectl get nodes
  register: kubectl_get_nodes
  when: kubeadm_join is succeeded

