---
# Tasks for common node setup

- name: Update /etc/hosts on all nodes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Check if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_needed
  ignore_errors: True

- name: Install docker if not installed
  script: "files/get-docker.sh {{ docker_ce_version }}"
  when: docker_needed.stat.exists == False
  register: docker_installed

- name: Disable swap filesystem
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: CONF_SWAPSIZE=0

- name: Enable cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    upgrade: full

- name: python-apt dependency
  shell: apt-get install -y python-apt
  args:
    warn: no

- name: Reboot
  reboot:
    reboot_timeout: 3600
